version: "3.7"
services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/home/node/app
      - /home/node/app/node_modules
    environment:
      - NODE_ENV=development
    # tty: true
    # stdin_open: true
